<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'DBCon' => $baseDir . '/code_vendors/pekky/DB/DBCon.class.php',
    'Query' => $baseDir . '/code_vendors/pekky/DB/Query.class.php',
);
