<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit28772b5b39ce6dfe453bb329cd48f8b3
{
    public static $classMap = array (
        'DBCon' => __DIR__ . '/../..' . '/code_vendors/pekky/DB/DBCon.class.php',
        'Query' => __DIR__ . '/../..' . '/code_vendors/pekky/DB/Query.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit28772b5b39ce6dfe453bb329cd48f8b3::$classMap;

        }, null, ClassLoader::class);
    }
}
